### ISSUE TITLE
export only ASCII in `Experiment` json

### ISSUE THREAD

**Issue by nsiles** [cgevans/mixes#31] opened 2022-11-18 16:53 UTC
On Windows there is a common error of this form: `UndefinedUnitError: 'ÂµM' is not defined in the unit registry`. It appears to stem from the use of Unicode such as µ.

There may be some fix, I'm not sure, but an easy way to ensure people don't get these errors is to output only ASCII, e.g., `uM` instead of `µM` whenever JSON is exported.

**Comment by cgevans** [comment] 2022-11-18 17:02
Do you know exactly when you get these errors (eg, could you paste an example backtrace)?  If so, I can make sure that this doesn't happen.  Is it just during JSON export/import, or are there other situations?

**Comment by cgevans** [comment] 2022-11-18 17:20
I think what I've just done should fix the problem in the main branch; let me know if it works.

**Comment by nsiles** [comment] 2022-11-18 17:28
Thank you for looking into this! Below is the traceback just in case. :)

```python
---------------------------------------------------------------------------
UndefinedUnitError                        Traceback (most recent call last)
Cell In [15], line 5
      1 #noexport
      2 # load old experiment with monomer and adapter mixes and put them in current experiment
      3 
      4 #old_experiment = Experiment.load('../sds04-30-monomers-anneal-and-ligate-agarose/sds04_ascii.json')
----> 5 old_experiment = Experiment.load('../sds04-30-monomers-anneal-and-ligate-agarose/sds04.json')
      6 experiment = Experiment()
      7 monomer_mix_1uM = old_experiment['monomers 1uM']

File ~\OneDrive\Nadia Documents\Git\mixes\src\alhambra_mixes\experiments.py:243, in Experiment.load(cls, filename_or_stream)
    240     s = filename_or_stream
    241     close = False
--> 243 exp = cls._structure(json.load(s))
    244 if close:
    245     s.close()

File ~\OneDrive\Nadia Documents\Git\mixes\src\alhambra_mixes\experiments.py:225, in Experiment._structure(cls, d)
    223 del d["class"]
    224 for k, v in d["components"].items():
--> 225     d["components"][k] = _structure(v)
    226 return cls(**d)

File ~\OneDrive\Nadia Documents\Git\mixes\src\alhambra_mixes\dictstructure.py:27, in _structure(x, experiment)
     25 del x["class"]
     26 if hasattr(c, "_structure"):
---> 27     return c._structure(x, experiment)
     28 for k in x.keys():
     29     x[k] = _structure(x[k])

File ~\OneDrive\Nadia Documents\Git\mixes\src\alhambra_mixes\mixes.py:981, in Mix._structure(cls, d, experiment)
    976 @classmethod
    977 def _structure(
    978     cls, d: dict[str, Any], experiment: "Experiment" | None = None
    979 ) -> "Mix":
    980     for k, v in d.items():
--> 981         d[k] = _structure(v, experiment)
    982     return cls(**d)

File ~\OneDrive\Nadia Documents\Git\mixes\src\alhambra_mixes\dictstructure.py:32, in _structure(x, experiment)
     30     return c(**x)
     31 elif isinstance(x, list):
---> 32     return [_structure(y) for y in x]
     33 else:
     34     return x

File ~\OneDrive\Nadia Documents\Git\mixes\src\alhambra_mixes\dictstructure.py:32, in <listcomp>(.0)
     30     return c(**x)
     31 elif isinstance(x, list):
---> 32     return [_structure(y) for y in x]
     33 else:
     34     return x

File ~\OneDrive\Nadia Documents\Git\mixes\src\alhambra_mixes\dictstructure.py:27, in _structure(x, experiment)
     25 del x["class"]
     26 if hasattr(c, "_structure"):
---> 27     return c._structure(x, experiment)
     28 for k in x.keys():
     29     x[k] = _structure(x[k])

File ~\OneDrive\Nadia Documents\Git\mixes\src\alhambra_mixes\actions.py:236, in ActionWithComponents._structure(cls, d, experiment)
    234         scomps.append(c)
    235     else:
--> 236         scomps.append(_structure(cd))
    237 d["components"] = scomps
    238 for k in d.keys():

File ~\OneDrive\Nadia Documents\Git\mixes\src\alhambra_mixes\dictstructure.py:27, in _structure(x, experiment)
     25 del x["class"]
     26 if hasattr(c, "_structure"):
---> 27     return c._structure(x, experiment)
     28 for k in x.keys():
     29     x[k] = _structure(x[k])

File ~\OneDrive\Nadia Documents\Git\mixes\src\alhambra_mixes\components.py:200, in Component._structure(cls, d, experiment)
    198 for k, v in d.items():
    199     d[k] = _structure(v, experiment)
--> 200 return cls(**d)

File <attrs generated init alhambra_mixes.components.Strand>:3, in __init__(self, name, concentration, sequence, plate, well)
      1 def __init__(self, name, concentration=attr_dict['concentration'].default, sequence=attr_dict['sequence'].default, *, plate=attr_dict['plate'].default, well=attr_dict['well'].default):
      2     _setattr(self, 'name', name)
----> 3     _setattr(self, 'concentration', __attr_converter_concentration(concentration))
      4     _setattr(self, 'plate', __attr_converter_plate(plate))
      5     _setattr(self, 'well', __attr_converter_well(well))

File ~\OneDrive\Nadia Documents\Git\mixes\src\alhambra_mixes\units.py:104, in _parse_conc_optional(v)
    101 """Parses a string or Quantity as a concentration; if None, returns a NaN
    102 concentration."""
    103 if isinstance(v, str):
--> 104     q = ureg.Quantity(v)
    105     if not q.check(nM):
    106         raise ValueError(f"{v} is not a valid quantity here (should be molarity).")

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pint\facets\plain\quantity.py:209, in PlainQuantity.__new__(cls, value, units)
    207 if units is None and isinstance(value, str):
    208     ureg = SharedRegistryObject.__new__(cls)._REGISTRY
--> 209     inst = ureg.parse_expression(value)
    210     return cls.__new__(cls, inst)
    212 if units is None and isinstance(value, cls):

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pint\facets\plain\registry.py:1255, in PlainRegistry.parse_expression(self, input_string, case_sensitive, use_decimal, **values)
   1252 input_string = string_preprocessor(input_string)
   1253 gen = tokenizer(input_string)
-> 1255 return build_eval_tree(gen).evaluate(
   1256     lambda x: self._eval_token(x, case_sensitive=case_sensitive, **values)
   1257 )

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pint\pint_eval.py:115, in EvalTreeNode.evaluate(self, define_op, bin_op, un_op)
    113         raise DefinitionSyntaxError('missing binary operator "%s"' % op_text)
    114     left = self.left.evaluate(define_op, bin_op, un_op)
--> 115     return bin_op[op_text](left, self.right.evaluate(define_op, bin_op, un_op))
    116 elif self.operator:
    117     # unary operator
    118     op_text = self.operator[1]

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pint\pint_eval.py:124, in EvalTreeNode.evaluate(self, define_op, bin_op, un_op)
    121     return un_op[op_text](self.left.evaluate(define_op, bin_op, un_op))
    122 else:
    123     # single value
--> 124     return define_op(self.left)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pint\facets\plain\registry.py:1256, in PlainRegistry.parse_expression.<locals>.<lambda>(x)
   1252 input_string = string_preprocessor(input_string)
   1253 gen = tokenizer(input_string)
   1255 return build_eval_tree(gen).evaluate(
-> 1256     lambda x: self._eval_token(x, case_sensitive=case_sensitive, **values)
   1257 )

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pint\facets\plain\registry.py:1142, in PlainRegistry._eval_token(self, token, case_sensitive, use_decimal, **values)
   1137         return self.Quantity(values[token_text])
   1138     else:
   1139         return self.Quantity(
   1140             1,
   1141             self.UnitsContainer(
-> 1142                 {self.get_name(token_text, case_sensitive=case_sensitive): 1}
   1143             ),
   1144         )
   1145 elif token_type == NUMBER:
   1146     return ParserHelper.eval_token(token, non_int_type=self.non_int_type)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pint\facets\plain\registry.py:588, in PlainRegistry.get_name(self, name_or_alias, case_sensitive)
    586 candidates = self.parse_unit_name(name_or_alias, case_sensitive)
    587 if not candidates:
--> 588     raise UndefinedUnitError(name_or_alias)
    589 elif len(candidates) == 1:
    590     prefix, unit_name, _ = candidates[0]

UndefinedUnitError: 'ÂµM' is not defined in the unit registry
```

**Comment by cgevans** [comment] 2022-11-21 14:25
Is this working for you now?  I don't have a good way of testing this, as it doesn't show up in our CI tests on Windows.

**Comment by dave-doty** [comment] 2022-11-21 14:32
Yes, this works now.

I suppose we could try to work out a unit test that reproduces it on Windows.

**Comment by cgevans** [comment] 2022-11-21 14:38
If you can, it might be useful, but I think we can close this now (I assume I didn't understand what ensure_ascii did, and thus set it to False when, in order to ensure unicode was preserved, it was safer to set it to True).  Coming up with a test to reproduce this might be tricky because it may rely on a particular Windows and Python configuration: the tests on Github already test JSON save+load on Windows, and µ should already be in there, but the tests have never had a problem with this.

**Closed as completed by cgevans** 2022-11-21 14:38 UTC

**Comment by dave-doty** [comment] 2022-11-24 16:16
> Coming up with a test to reproduce this might be tricky because it may rely on a particular Windows and Python configuration: the tests on Github already test JSON save+load on Windows, and µ should already be in there, but the tests have never had a problem with this.

Both Nadia and I use Anaconda, and we both encounter this error when loading Unicode, no idea if the problem is specific to this installation. But probably it's not a big deal now that it's using `ensure_ascii`; if we encounter a similar problem in the future we can try to get to the bottom of it.

**Comment by nsiles** [comment] 2022-11-25 02:16
I am pretty sure I use pip and not anaconda >_< unless you know something I don’t…

Sent from my iPhone

On Nov 24, 2022, at 10:16 AM, David Doty ***@***.***> wrote:

﻿

Coming up with a test to reproduce this might be tricky because it may rely on a particular Windows and Python configuration: the tests on Github already test JSON save+load on Windows, and µ should already be in there, but the tests have never had a problem with this.

Both Nadia and I use Anaconda, and we both encounter this error when loading Unicode, no idea if the problem is specific to this installation. But probably it's not a big deal now that it's using ensure_ascii; if we encounter a similar problem in the future we can try to get to the bottom of it.
